<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />

<title>Applied Economics with R for UoB students</title>

<!-- HEAD_CONTENT -->

<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->



</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-welcome" class="section level2">
<h2>Welcome!</h2>
<p>Hi!</p>
<p>This tutorial is written for Applied Economics students at the
University of Bristol.</p>
<p><strong>How this works</strong></p>
<ul>
<li>There are two tutorials. This one is the <strong>dynamic</strong>
version. To try the <strong>static</strong> version go to: <a
href="https://hhsievertsen.github.io/applied_econ_with_r/">hhsievertsen.github.io/applied_econ_with_r/</a>
(they cover the same material).</li>
<li>The tutorial aims at covering the same methods we covered in Stata
during the term.</li>
<li>All data used is directly downloadable. You should therefore be able
to download the data and try the methods in R on your own computer.</li>
<li>The tutorial mainly consists of code blocks and the resulting
output. Every now and then I include some references to how I would do
the same task in Stata or key differences to Stata.</li>
</ul>
<p>I appreciate feedback, thanks.</p>
<p>Hans (November 15 , 2022)</p>
<p><br><br><br><br><br><br></p>
</div>
<div id="section-research-question-data" class="section level2">
<h2>1 Research question &amp; data</h2>
<p>You will only see the above content in the output.</p>
<div id="section-the-research-question" class="section level3">
<h3>1.1 The research question</h3>
<p>Our goal is to answer the following <strong>fictitious</strong>
research question:</p>
<blockquote>
<p>Does attending a summer school improve test scores?</p>
</blockquote>
<p>The research question will be addressed using a <strong>fictitious
simulated</strong> dataset.</p>
</div>
<div id="section-the-fictitious-setting" class="section level3">
<h3>1.2 The fictitious setting</h3>
<p>The research question is inspired by papers such as <a
href="https://www.sciencedirect.com/science/article/pii/S0304407607001194?casa_token=hnnF764CKPoAAAAA:5b9WhCManNDsdW4SmOHnnzNr0fZIarW8s6EsvpQW7MdUt470eNPmN2T8IFCsNc6Iajew5tEeNA">Matsudaira
(2007)</a> and the survey on interventions for low SES students by by <a
href="https://journals.sagepub.com/doi/abs/10.3102/0034654316687036">Dietrichson
et al ( 2017)</a>.</p>
<p>The <strong>fictitious</strong> setting is as follows:</p>
<ul>
<li>In the summer break between year 5 and year 6, (roughly
corresponding to age 10) there is an optional summer school.</li>
<li>The summer school could be focusing on the school curriculum, or it
could be focused on skills that lead to improved schooling outcomes (for
example “grit” as in <a
href="https://academic.oup.com/qje/article-abstract/134/3/1121/5342089?redirectedFrom=fulltext">Alan
et al (2019)</a>).</li>
<li>The summer school is free, but enrollment requires active
involvement by parents.</li>
<li>We are interested in whether participation in the summer school
improves child outcomes.</li>
</ul>
</div>
<div id="section-the-fictitious-data" class="section level3">
<h3>1.3 The fictitious data</h3>
<p>We have three datasets to study the research question:</p>
<ol style="list-style-type: decimal">
<li><a
href="https://raw.githubusercontent.com/hhsievertsen/applied_econ_with_r/main/data/school_data_1.csv">school_data_1.csv</a></li>
</ol>
<ul>
<li>We use this as example on how to <strong>load data stored in a csv
format</strong>.</li>
<li>This dataset contains information about person id, school id, an
indicator variable that takes the value of 1 if the individual
participated in the summer school, information about gender, parental
income and parental schooling, and test scores in year 5 (before the
treatment) and year 6.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li><a
href="https://github.com/hhsievertsen/applied_econ_with_r/raw/main/data/school_data_2.dta">school_data_2.dta</a></li>
</ol>
<ul>
<li>We use this as example on <strong>how to load data stored in Stata
format</strong>.</li>
<li>This dataset contains information about person id, which enables us
to link it to the first dataset. We will use this to practice
<strong>merging</strong> data.</li>
<li>The dataset also contains information about whether the individual
received a reminder letter.</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li><a
href="https://github.com/hhsievertsen/applied_econ_with_r/raw/main/data/school_data_3.xlsx">school_data_3.xlsx</a></li>
</ol>
<ul>
<li>We use this as example on how to <strong>load data stored in a
Microsoft Excel format</strong>.</li>
<li>This dataset contains information about person id, which enables us
to link it to the first dataset.</li>
<li>The dataset also contains information about test scores in earlier
(&lt;5) and later years (&gt;6).</li>
</ul>
<p>Let’s get started!</p>
<p><br><br><br><br><br><br></p>
</div>
</div>
<div id="section-loading-merging-the-data" class="section level2">
<h2>2 Loading &amp; merging the data</h2>
<div id="section-installing-and-loading-a-package"
class="section level3">
<h3>2.1 Installing and loading a “package”</h3>
<p>The first item on our to do list is to load the datasets. The first
dataset is in a csv format. There are several ways to load a csv
document into R. I am going to use <code>read_csv()</code> from the
<em>readr</em> package. Before we can use this package we need to
install it. We install a package with the
<code>install.packages()</code> function, where we insert the name of
the package in parenthesis. This procedure corresponds to <em>ssc
install outreg</em> to install outreg in Stata.</p>
<p>An important difference to Stata is that we also have to tell R to
use the new package in every new session. We do that with
<code>library()</code>. However we only have to install it once. So to
install and load <em>readr</em> we run the following command:</p>
<pre class="r"><code>install.packages(&quot;readr&quot;)</code></pre>
<p>To load the <em>readr</em> package we run the following command:</p>
<pre class="r"><code>library(&quot;readr&quot;)</code></pre>
<p>While we only have to install a package once on each computer, we
have load it in every new session.</p>
</div>
<div id="section-loading-a-csv-data-file" class="section level3">
<h3>2.2 Loading a csv data file</h3>
<p>Having installed <em>readr</em> we are now ready to use the
<code>read_csv()</code> function to load our first dataset. We will load
the dataset <em>school_data_1.csv</em> by inserting the path to the file
in the parenthesis. In the example below we first load the
<em>readr</em> package to illustrate that we have to load it in every
new session. However, in later code blocks we’ll leave out the
<code>library()</code> call for packages that have already been
loaded.</p>
<p>PS. note also that we include comments in code block below. Comments
are lines that R ignores and these lines always start with a
<code>#</code> symbol.</p>
<pre class="r"><code># load readr package
library(&quot;readr&quot;)
# load data
read_csv(&quot;C:/Users/hhs/school_data_1.csv&quot;)</code></pre>
<pre><code>## # A tibble: 3,491 × 8
##    person_id school_id summercamp female parental_schooling parental_lincome
##        &lt;int&gt;     &lt;int&gt;      &lt;dbl&gt;  &lt;dbl&gt;              &lt;dbl&gt;            &lt;dbl&gt;
##  1         1         5          0      1                 10             12.9
##  2         2        14          1      0                 11             14.7
##  3         3         7          1      0                 14             16.1
##  4         4         8          0      0                 12             14.6
##  5         5         9          1      0                 11             13.8
##  6         6        26          1      1                 11             14.7
##  7         7        13          1      1                 11             14.4
##  8         8        11          0      1                 13             15.0
##  9         9        23          1      1                 11             14.3
## 10        10         9          1      1                 11             13.8
## # … with 3,481 more rows, and 2 more variables: test_year_5 &lt;dbl&gt;,
## #   test_year_6 &lt;dbl&gt;</code></pre>
<p>Stata users would now expect that the dataset is loaded in the memory
and everything I do now relates to this dataset. Stata users will be
disappointed. When R executes the command above it loads the data, but
then it says: “Hey, Hans didn’t tell me what to do with the dataset, so
I will just print the contents of it and forget it.”</p>
<p>While Stata (at least in older versions) is based on having one
dataset loaded at a time, we can have many datasets loaded at once in R.
Therefore, to identify the dataset we need to give it a name. In this
example we tell R to store the new dataset under the name
<em>school_data_1</em> we use the <em>assignment operator</em>
<code>&lt;-</code>, but <code>=</code> would also work. However, it is a
good habit to use the assignment operator, because it makes life a bit
easier in more advanced situations that will meet later on your R
journey (not in this tutorial).</p>
<pre class="r"><code># load data and assign it to an object with the name school_data_1
school_data_1&lt;-read_csv(&quot;C:/Users/hhs/school_data_1.csv&quot;)</code></pre>
<p>In Stata my first step after loading the data is typically to use
<em>browse</em> to take a look at the data. In R we can do that with
<code>View(school_data_1)</code>. I will not show that command here.
Instead I will present the function <code>head()</code> that prints the
head of the dataset with the first 6 rows.</p>
<pre class="r"><code># Use head() to print first 6 observations of school_data_1
head(school_data_1)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["person_id"],"name":[1],"type":["int"],"align":["right"]},{"label":["school_id"],"name":[2],"type":["int"],"align":["right"]},{"label":["summercamp"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["female"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["parental_schooling"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["parental_lincome"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["test_year_5"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["test_year_6"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"5","3":"0","4":"1","5":"10","6":"12.93921","7":"NA","8":"1.544524"},{"1":"2","2":"14","3":"1","4":"0","5":"11","6":"14.73739","7":"1.279436","8":"2.469689"},{"1":"3","2":"7","3":"1","4":"0","5":"14","6":"16.08326","7":"2.744308","8":"3.434242"},{"1":"4","2":"8","3":"0","4":"0","5":"12","6":"14.60808","7":"1.755313","8":"2.289302"},{"1":"5","2":"9","3":"1","4":"0","5":"11","6":"13.75679","7":"1.162756","8":"1.868058"},{"1":"6","2":"26","3":"1","4":"1","5":"11","6":"14.70552","7":"2.422202","8":"2.718811"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="section-loading-a-stata-data-file" class="section level3">
<h3>2.3 Loading a Stata data file</h3>
<p>We will now load a Stata dataset into R. To load a <em>dta</em> file
I will use the <code>read.dta13()</code> function from the
<em>readstata13</em> package. The syntax is then very similar to the
<code>read_csv()</code> syntax. This time we will use
<code>tail()</code> to show the last 8 observations.</p>
<pre class="r"><code># load readstata13
library(&quot;readstata13&quot;)
# use read.dta13 from readstata13 to load a Stata dataset
school_data_2&lt;- read.dta13(&quot;C:/Users/hhs/school_data_2.dta&quot;)
# print the 8 rows in the tail
tail(school_data_2,n=8)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["person_id"],"name":[1],"type":["int"],"align":["right"]},{"label":["letter"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"3484","2":"0"},{"1":"3485","2":"0"},{"1":"3486","2":"1"},{"1":"3487","2":"0"},{"1":"3488","2":"1"},{"1":"3489","2":"0"},{"1":"3490","2":"0"},{"1":"3491","2":"0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="section-loading-an-xlsx-file" class="section level3">
<h3>2.4 Loading an xlsx file</h3>
<p>Finally, we’ll load the the <em>xlsx</em> file
<em>school_data_3.xlsx</em> for that we’ll use the
<code>read.xlsx()</code> function from the <em>openxlsx</em> package.
Again, the syntax is very similar to what we’ve seen before. This time
we will use the <code>glimpse()</code> function from the <em>dplyr</em>
package to get a glimpse of the dataset.</p>
<pre class="r"><code># Load openxlsx and dplyr
library(&quot;openxlsx&quot;)
library(&quot;dplyr&quot;)
# Use read.xlsx from openxlsx to load .xlsx file
school_data_3 &lt;- read.xlsx(&quot;C:/Users/hhs/school_data_3.xlsx&quot;)
# use glimpse to get a &quot;glimpse&quot; of the loaded dataset
glimpse(school_data_3)</code></pre>
<pre><code>## Rows: 3,491
## Columns: 10
## $ person_id    &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…
## $ test_year_2  &lt;dbl&gt; 1.090117, 1.246309, 2.726472, 2.693032, 1.660545, 2.22377…
## $ test_year_3  &lt;dbl&gt; 1.914594, 1.154470, 2.269011, 2.413203, 1.828067, 2.27566…
## $ test_year_4  &lt;dbl&gt; 2.065805, 1.582455, 3.247252, 1.479452, 1.361972, 2.38510…
## $ test_year_7  &lt;dbl&gt; 2.377697, 1.747376, 3.017764, 2.637954, 1.904636, 3.37613…
## $ test_year_8  &lt;dbl&gt; 2.032904, 2.444041, 3.361646, 3.021940, 2.109774, 3.24542…
## $ test_year_9  &lt;dbl&gt; 1.493803, 1.663050, 3.387020, 2.761513, 2.285818, 2.96503…
## $ test_year_10 &lt;dbl&gt; 1.880512, 1.833769, 2.968617, 2.088086, 1.845694, 3.30819…
## $ learnings    &lt;dbl&gt; 10.236394, 8.278911, 8.966529, 8.876466, 8.770518, 10.484…
## $ school_id    &lt;int&gt; 5, 14, 7, 8, 9, 26, 13, 11, 23, 9, 25, 15, 3, 4, 17, 7, 1…</code></pre>
</div>
<div id="section-merging-the-datasets" class="section level3">
<h3>2.5 Merging the datasets</h3>
<p>Let’s now merge the three datasets. We will use the
<code>merge()</code> function for that. In merge we first state the
names of the two datasets to merge. We then tell R the column(s) to use
to merge the two datasets with <code>by=....</code>. As a default R
includes all rows that are observed in both datasets (based on the by
variable), but we can set <code>all=TRUE</code> to keep all rows from
both datasets, or <code>all.x=TRUE</code> to keep all rows from the
first dataset and all rows that were merged, and finally
<code>all.y=TRUE</code> to keep all rows from the second dataset. The
default behaviour of R corresponds to using the option <em>keep(3)</em>
in Stata, and Stata’s default option corresponds to using
<code>all=TRUE</code> in R.</p>
<p>Here as example where merge the first two datasets. We then use the
<code>dim()</code> function to get the dimensions of the new merged
dataset in terms of the number of rows and the number of columns.</p>
<p>And hey, this is the first dynamic code block. You can edit the code
(there is no need in this case) and click Run Code to see what
happens.</p>
<div class="tutorial-exercise" data-label="ch2-9b" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># merge school_data_1 with school_data_2
school_data_merged&lt;-merge(school_data_1,school_data_2,by=&quot;person_id&quot;)
dim(school_data_merged)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="ch2-9b-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># dimensions of school_data_1
dim(school_data_1)</code></pre>
</div>
<p>We note that the merged dataset has 3491 rows and 9 columns. We
actually didn’t check the number of rows in the raw datasets (that would
have been a good thing to do; maybe you can do it by changing the code
above?). If all rows are merged we should have the same number of rows
as in the original dataset. From above we knew that
<em>school_data_1</em> has 8 columns and by merging the
<em>school_data_2</em> on we also get the column with the information
about whether the family receiving the letter, making it to in total 9
columns.</p>
<p><strong>Important difference to Stata:</strong> A key difference
between Stata and R merge is that in case a variable in the first
dataset has the same name as a column in the second dataset, R will
automatically rename the column names by adding suffices <em>.x</em>
(the column from the first dataset) and <em>.y</em> (the column from the
second dataset). Stata just overwrites the columns.</p>
<p>Now it is your turn, in the block below we want to</p>
<ol style="list-style-type: decimal">
<li>Merge <em>school_data_1</em> and <em>school_data_2</em> by the
<em>person_id</em> column and save the merged dataset under the name
<em>school_data</em>.</li>
<li>Merge <em>school_data_3</em> with <em>school_data</em> and overwrite
<em>school_data</em>. Note in this case we merge by <em>person_id</em>
and <em>school_id</em> columns. This is not necessary (because person_id
is unique), but serves as an example on how to merge by more columns
using <code>c()</code>. name <em>school_data</em>.</li>
<li>Use the <code>summary()</code> function to obtain summary statistics
of the variables.</li>
</ol>
<div class="tutorial-exercise" data-label="ch2-10" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Merge school_data_1 and school_data_2 and save as school_data_merged

# Merge school_data_3 with school_data_merged

# summary statistics</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="ch2-10-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Merge school_data_1 and school_data_2 and save as school_data_merged 
school_data_merged&lt;-merge(school_data_1,school_data_2,by=&quot;person_id&quot;)</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="ch2-10-hint-2"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Merge school_data_1 and school_data_2 and save as school_data_merged 
school_data_merged&lt;-merge(school_data_1,school_data_2,by=&quot;person_id&quot;)
# Merge school_data_3 with school_data_merged
school_data_merged&lt;-merge(school_data_merged,school_data_3,by=c(&quot;person_id&quot;,&quot;school_id&quot;))</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="ch2-10-hint-3"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Merge school_data_1 and school_data_2 and save as school_data_merged 
school_data_merged&lt;-merge(school_data_1,school_data_2,by=&quot;person_id&quot;)
# Merge school_data_3 with school_data_merged
school_data_merged&lt;-merge(school_data_merged,school_data_3,by=c(&quot;person_id&quot;,&quot;school_id&quot;))
# summary statistics
summary(school_data_merged)</code></pre>
</div>
<p><br></p>
</div>
</div>
<div id="section-cleaning-the-data" class="section level2">
<h2>3 Cleaning the data</h2>
<div id="section-tidying-the-data" class="section level3">
<h3>3.1 Tidying the data</h3>
<p>Now that we have merged the datasets, we want to make sure that the
merged dataset satisfies the <a
href="https://vita.had.co.nz/papers/tidy-data.pdf">Tidy Data
Principles</a>. From these principles we know that the number of columns
should correspond to the number of variables in the dataset. But how
many variables are there?</p>
<p><div class="panel-heading tutorial-quiz-title">Quiz</div></p>
<div class="panel panel-default">
<div data-label="quiz-1" class="tutorial-question panel-body">
<div id="quiz-1-answer_container" class="shiny-html-output"></div>
<div id="quiz-1-message_container" class="shiny-html-output"></div>
<div id="quiz-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<p>Let’s now compare the number of variables to the number of
columns:</p>
<div class="tutorial-exercise" data-label="ch3-1e" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Use the dim() functions to get the number of rows and columns</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="ch3-1e-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Use the dim() functions to get the number of rows and columns
dim(school_data_merged)</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="ch3-1e-hint-2"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Alternatively we can use the nrow() functions to get the number of columns
ncol(school_data_merged)</code></pre>
</div>
<p>Oh no! The number of columns does not correspond to the number of
variables. Let’s sort this out. The issue is that the variables
<em>test_year_5</em> contain information about the test score and the
year. We need to separate this out. We can use tools from the
<em>tidyr</em> package to make the dataset tidy. Specifically, we use
<code>pivot_longer()</code> which corresponds to <em>reshape long</em>
in Stata. See also section 9.2 in the <a
href="https://hhsievertsen.shinyapps.io/r_introduction/">R
introduction</a> for details.</p>
<pre class="r"><code># load tidyr package
library(&quot;tidyr&quot;)
# make data tidy (make long)
school_data_tidy&lt;-school_data_merged%&gt;%
       pivot_longer(
         cols = starts_with(&quot;test_year&quot;),
         names_to = &quot;year&quot;,
         names_prefix = &quot;test_year_&quot;,
         names_transform = list(year = as.integer),
         values_to = &quot;test_score&quot;,
       )
# ncol to get the number of columns of the new dataset
ncol(school_data_tidy)</code></pre>
<pre><code>## [1] 10</code></pre>
<p>Hurray! We now have a dataset where the number columns correspond to
the number of variables.</p>
</div>
<div id="section-sample-selection" class="section level3">
<h3>3.2 Sample Selection</h3>
<p>We now have a dataset that satisfies the tidy data principles. The
next task before is the sample selection. The only sample selection we
are concerned with in this exercise is missing values. We will use the
<code>skim()</code> function to assess how many missing values there are
in our dataset. <code>skim()</code> is one of my favourite functions in
R to get an overview of the datasets, it comes from the <em>skimr</em>
package.</p>
<div class="tutorial-exercise" data-label="ch3-3" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Load skimr
library(&quot;skimr&quot;)
# Use skim() to skim the data
skim(school_data_tidy)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>We can easily observe how many rows and columns there are, the
variable types, the number of missing values. The mean, standard
deviations, percentiles, and we even get a small histogram.</p>
<p>We observe that the column <em>parental_schooling</em> has 45 missing
values and the variable <em>test_score</em> has 11 missing values. Let’s
assume that these values are missing at random and remove these rows.
Here we use <code>filter()</code> for that. The <code>filter()</code>
function takes two arguments. First, the name of the original dataset,
and secondly the condition a row must satisfy to be kept in the
filtering process. The condition we want to satisfy is that
<code>!is.na(parental_schooling)</code>. The <code>is.na()</code> is a
function is true if the element in <code>( )</code> is missing. We use
the <code>!</code> to achieve the opposite of that. In other words that
parental schooling is not missing.</p>
<div class="tutorial-exercise" data-label="ch3-4" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Select only rows with no missing values
school_data_selected&lt;-filter(school_data_tidy,!is.na(parental_schooling),!is.na(test_score))
# Use skim() to skim the data again
skim(school_data_selected)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Very good! We’ve now created a new dataset containing only complete
cases. Let’s now create a nice looking table.</p>
</div>
<div id="section-modifying-the-data" class="section level3">
<h3>3.3 Modifying the data</h3>
<p>Our next step is to make some modifications to the data. First, we
will rename the <em>summercamp</em> variable to <em>summerschool</em>.
We do that with the <code>rename()</code> function. The
<code>rename()</code> function has a similar syntax to filter. We first
state the name of the original dataset and then the rename
expression.</p>
<div class="tutorial-exercise" data-label="ch3-5" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># rename summercamp to summerschool
analysisdata&lt;-rename(school_data_selected, summerschool=summercamp)
# use head to view the first 6 observations 
head(analysisdata)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Brilliant. In the next step we want to transform our
<em>test_score</em> variable to have mean of zero and a standard
deviation of one. Importantly we want to do this standardization within
year. In Stata this would be a task for <em>bys year:</em>. In Stata we
first specify what variable to group the data on, and the apply the
functions <em>sd</em> and <em>mean</em> on that level.</p>
<div class="tutorial-exercise" data-label="ch3-6" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Standardize test score
# Group analysisdata by year
analysisdata&lt;-group_by(analysisdata,year)
# Create a new variable with mutate
analysisdata&lt;-mutate(analysisdata, test_score=(test_score-mean(test_score))/sd(test_score))
# show mean of test_score
print(paste(&quot;Mean of test score:&quot;,mean(analysisdata$test_score)))
#show sd of test_score
print(paste(&quot;SD of test score:&quot;,sd(analysisdata$test_score)))</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>In the example above we use</p>
<ul>
<li><code>print()</code> to print output to the console (just like
<em>display</em> in Stata).</li>
<li><code>paste()</code> to concatenate elements together</li>
<li><code>analysisdata$test_score</code> to extract the variable
<em>test_score</em> from the <em>analysisdata</em> dataset.</li>
<li><code>mean()</code> and <code>sd()</code> to calculate means and
standard deviations. Note that this only works because we already
removed the missing values. If we apply <code>mean()</code> on a vector
that includes missing values it will return a missing value unless we
specify the option <code>na.rm = FALSE</code>.</li>
</ul>
</div>
</div>
<div id="section-descriptive-statistics" class="section level2">
<h2>4 Descriptive Statistics</h2>
<p>We’ve now managed to load <em>csv</em>, <em>dta</em>, and
<em>xlsx</em> files. We’ve also managed to merge them, restructure the
dataset, and we have removed missing values. The next step in our
empirical project is to create some tables and charts to describe the
dataset.</p>
<p>Our goal is to create a table that shows means, standard deviations,
and other statistics that gives us and the reader an impression of the
dataset. We already know at least two ways to calculate summary
statistics:</p>
<ol style="list-style-type: decimal">
<li><p><code>summary()</code> from base R. This function actually works
on a lot of object types in R. It always gives a good summary. But our
goal is to create a table that we can include in a Microsoft Word or
Latex document.</p></li>
<li><p><code>skim()</code> from the <em>skimr</em> package.</p></li>
</ol>
<div id="section-a-quick-way-to-create-a-nice-looking-table"
class="section level3">
<h3>4.1 A quick way to create a nice looking table</h3>
<p>We will first use a cousin of <code>skim()</code> to create a table
with summary statistics that can be exported to various formats,
included Latex. The cousin comes from the <em>modelsummary</em> package
and is called <code>datasummary_skim()</code>. Let’s first create the
default table:</p>
<div class="tutorial-exercise" data-label="ch4-1" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># load modelsummary
library(&quot;modelsummary&quot;)
# create a summary stat table
analysisdata%&gt;%
  filter(year==2)%&gt;%
  select(female,starts_with(&quot;paren&quot;),letter,summerschool,test_score)%&gt;%
  datasummary_skim()</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Let’s change the appearance of the table and export it to Word. When
exporting it to Latex, we can’t have histogram’, so we disable them. We
specify <code>output="docx"</code> to write to a Word file. We can also
export the table to other formats like LaTex.</p>
<pre class="r"><code># load modelsummary
library(&quot;modelsummary&quot;)
# create a summary stat table in Latex format
analysisdata%&gt;%
  filter(year==2)%&gt;%
  select(female,starts_with(&quot;paren&quot;),letter,summerschool,test_score)%&gt;%
  datasummary_skim( fmt=&quot;%.2f&quot;,
                 histogram=FALSE, output=&quot;tab_summary_statistics.docx&quot;)</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Unique (#)
</th>
<th style="text-align:right;">
Missing (%)
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
Min
</th>
<th style="text-align:right;">
Median
</th>
<th style="text-align:right;">
Max
</th>
<th style="text-align:right;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2.00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
2.00
</td>
<td style="text-align:right;">
2.00
</td>
<td style="text-align:right;">
2.00
</td>
<td style="text-align:right;">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="svglite" width="48.00pt" height="12.00pt" viewBox="0 0 48.00 12.00">
<defs>
<style type="text/css">
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  </style>
</defs><rect width="100%" height="100%" style="stroke: none; fill: none;"></rect><defs><clipPath id="cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw"><rect x="0.00" y="0.00" width="48.00" height="12.00"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw)">
</g><defs><clipPath id="cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw"><rect x="0.00" y="2.88" width="48.00" height="9.12"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw)"><rect x="-31.56" y="3.22" width="55.56" height="8.44" style="stroke-width: 0.38; fill: #000000;"></rect></g>
</svg>
</td>
</tr>
<tr>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.52
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="svglite" width="48.00pt" height="12.00pt" viewBox="0 0 48.00 12.00">
<defs>
<style type="text/css">
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  </style>
</defs><rect width="100%" height="100%" style="stroke: none; fill: none;"></rect><defs><clipPath id="cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw"><rect x="0.00" y="0.00" width="48.00" height="12.00"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw)">
</g><defs><clipPath id="cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw"><rect x="0.00" y="2.88" width="48.00" height="9.12"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw)"><rect x="1.78" y="3.73" width="4.44" height="7.94" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="6.22" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="10.67" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="15.11" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="19.56" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="24.00" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="28.44" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="32.89" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="37.33" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="41.78" y="3.22" width="4.44" height="8.44" style="stroke-width: 0.38; fill: #000000;"></rect></g>
</svg>
</td>
</tr>
<tr>
<td style="text-align:left;">
parental_schooling
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
11.32
</td>
<td style="text-align:right;">
1.10
</td>
<td style="text-align:right;">
10.00
</td>
<td style="text-align:right;">
11.00
</td>
<td style="text-align:right;">
23.00
</td>
<td style="text-align:right;">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="svglite" width="48.00pt" height="12.00pt" viewBox="0 0 48.00 12.00">
<defs>
<style type="text/css">
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  </style>
</defs><rect width="100%" height="100%" style="stroke: none; fill: none;"></rect><defs><clipPath id="cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw"><rect x="0.00" y="0.00" width="48.00" height="12.00"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw)">
</g><defs><clipPath id="cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw"><rect x="0.00" y="2.88" width="48.00" height="9.12"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw)"><rect x="1.78" y="3.22" width="3.42" height="8.44" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="5.20" y="9.46" width="3.42" height="2.20" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="8.62" y="10.86" width="3.42" height="0.80" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="12.03" y="11.39" width="3.42" height="0.27" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="15.45" y="11.55" width="3.42" height="0.12" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="18.87" y="11.60" width="3.42" height="0.065" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="22.29" y="11.65" width="3.42" height="0.014" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="25.71" y="11.65" width="3.42" height="0.014" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="29.13" y="11.66" width="3.42" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="32.55" y="11.66" width="3.42" height="0.0068" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="35.97" y="11.66" width="3.42" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="39.38" y="11.66" width="3.42" height="0.0034" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="42.80" y="11.66" width="3.42" height="0.0034" style="stroke-width: 0.38; fill: #000000;"></rect></g>
</svg>
</td>
</tr>
<tr>
<td style="text-align:left;">
parental_lincome
</td>
<td style="text-align:right;">
3486
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
14.56
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
12.67
</td>
<td style="text-align:right;">
14.52
</td>
<td style="text-align:right;">
19.45
</td>
<td style="text-align:right;">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="svglite" width="48.00pt" height="12.00pt" viewBox="0 0 48.00 12.00">
<defs>
<style type="text/css">
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  </style>
</defs><rect width="100%" height="100%" style="stroke: none; fill: none;"></rect><defs><clipPath id="cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw"><rect x="0.00" y="0.00" width="48.00" height="12.00"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw)">
</g><defs><clipPath id="cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw"><rect x="0.00" y="2.88" width="48.00" height="9.12"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw)"><rect x="0.68" y="11.52" width="3.28" height="0.14" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="3.96" y="10.44" width="3.28" height="1.22" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="7.23" y="7.25" width="3.28" height="4.41" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="10.51" y="3.29" width="3.28" height="8.37" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="13.79" y="3.22" width="3.28" height="8.44" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="17.06" y="7.61" width="3.28" height="4.06" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="20.34" y="10.13" width="3.28" height="1.54" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="23.62" y="11.14" width="3.28" height="0.53" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="26.89" y="11.40" width="3.28" height="0.26" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="30.17" y="11.60" width="3.28" height="0.058" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="33.44" y="11.62" width="3.28" height="0.042" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="36.72" y="11.66" width="3.28" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="40.00" y="11.65" width="3.28" height="0.017" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="43.27" y="11.65" width="3.28" height="0.0083" style="stroke-width: 0.38; fill: #000000;"></rect></g>
</svg>
</td>
</tr>
<tr>
<td style="text-align:left;">
letter
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
0.43
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="svglite" width="48.00pt" height="12.00pt" viewBox="0 0 48.00 12.00">
<defs>
<style type="text/css">
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  </style>
</defs><rect width="100%" height="100%" style="stroke: none; fill: none;"></rect><defs><clipPath id="cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw"><rect x="0.00" y="0.00" width="48.00" height="12.00"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw)">
</g><defs><clipPath id="cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw"><rect x="0.00" y="2.88" width="48.00" height="9.12"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw)"><rect x="1.78" y="3.22" width="4.44" height="8.44" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="6.22" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="10.67" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="15.11" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="19.56" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="24.00" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="28.44" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="32.89" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="37.33" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="41.78" y="8.89" width="4.44" height="2.77" style="stroke-width: 0.38; fill: #000000;"></rect></g>
</svg>
</td>
</tr>
<tr>
<td style="text-align:left;">
summerschool
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.46
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="svglite" width="48.00pt" height="12.00pt" viewBox="0 0 48.00 12.00">
<defs>
<style type="text/css">
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  </style>
</defs><rect width="100%" height="100%" style="stroke: none; fill: none;"></rect><defs><clipPath id="cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw"><rect x="0.00" y="0.00" width="48.00" height="12.00"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw)">
</g><defs><clipPath id="cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw"><rect x="0.00" y="2.88" width="48.00" height="9.12"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw)"><rect x="1.78" y="3.22" width="4.44" height="8.44" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="6.22" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="10.67" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="15.11" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="19.56" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="24.00" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="28.44" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="32.89" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="37.33" y="11.66" width="4.44" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="41.78" y="4.35" width="4.44" height="7.31" style="stroke-width: 0.38; fill: #000000;"></rect></g>
</svg>
</td>
</tr>
<tr>
<td style="text-align:left;">
test_score
</td>
<td style="text-align:right;">
3486
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
−0.00
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
−4.13
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
3.71
</td>
<td style="text-align:right;">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" class="svglite" width="48.00pt" height="12.00pt" viewBox="0 0 48.00 12.00">
<defs>
<style type="text/css">
    .svglite line, .svglite polyline, .svglite polygon, .svglite path, .svglite rect, .svglite circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
    .svglite text {
      white-space: pre;
    }
  </style>
</defs><rect width="100%" height="100%" style="stroke: none; fill: none;"></rect><defs><clipPath id="cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw"><rect x="0.00" y="0.00" width="48.00" height="12.00"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwwLjAwfDEyLjAw)">
</g><defs><clipPath id="cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw"><rect x="0.00" y="2.88" width="48.00" height="9.12"></rect></clipPath></defs><g clip-path="url(#cpMC4wMHw0OC4wMHwyLjg4fDEyLjAw)"><rect x="-0.32" y="11.65" width="2.83" height="0.012" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="2.51" y="11.66" width="2.83" height="0.00" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="5.35" y="11.59" width="2.83" height="0.073" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="8.18" y="11.41" width="2.83" height="0.26" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="11.01" y="11.07" width="2.83" height="0.60" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="13.85" y="9.85" width="2.83" height="1.81" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="16.68" y="7.63" width="2.83" height="4.03" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="19.51" y="5.36" width="2.83" height="6.30" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="22.35" y="3.95" width="2.83" height="7.71" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="25.18" y="3.22" width="2.83" height="8.44" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="28.01" y="4.90" width="2.83" height="6.77" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="30.85" y="7.82" width="2.83" height="3.85" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="33.68" y="10.10" width="2.83" height="1.56" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="36.51" y="10.97" width="2.83" height="0.69" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="39.35" y="11.43" width="2.83" height="0.23" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="42.18" y="11.59" width="2.83" height="0.073" style="stroke-width: 0.38; fill: #000000;"></rect><rect x="45.01" y="11.65" width="2.83" height="0.012" style="stroke-width: 0.38; fill: #000000;"></rect></g>
</svg>
</td>
</tr>
</tbody>
</table>
<p>Brilliant.</p>
</div>
<div id="section-custom-tables" class="section level3">
<h3>4.2 Custom tables</h3>
<p>To customize our table of summary statistics a bit more we can use
the function <code>datasummary()</code> (from the modelsummary package,
but we have already loaded that1). This function allows us to enter a
<em>formula</em> for the structure of our table. Try running the code
below and try also to make a change to also include the 75th percentile
and to include the <em>parental_lincome</em> variable.</p>
<div class="tutorial-exercise" data-label="merge3" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># create a summary stat table
datasummary(female+parental_schooling+
              letter+test_score~Factor(summerschool)*(Mean+SD),
            sparse_header = FALSE,
            data=filter(analysisdata,year==2))</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge3-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># create a summary stat table
datasummary(female+parental_schooling+parental_lincome+
              letter+test_score~Factor(summerschool)*(Mean+SD+P75),
            sparse_header = FALSE,
            data=filter(analysisdata,year==2))</code></pre>
</div>
<p>In the example above we</p>
<ul>
<li><p>List the variables to include separated with a
+:<code>female+parental_schooling+pa...</code></p></li>
<li><p>Use a <code>~</code> to separate the list of variables from the
formula.</p></li>
<li><p>Use the formula <code>Factor(summerschool)*(Mean+SD)</code> to
show that we want to show the mean and standard deviation separately for
each values of the variable <code>summerschool</code>. We use
<code>Factor()</code> to tell R that it should consider summerschool as
a binary variable. We could also have done that in the data tidying
process. We can also reverse the ordering
<code>(Mean+SD)*Factor(summerschool)</code>, which would then first show
the mean and standard deviation and then split by summerschool within
these values.</p></li>
<li><p>Use <code>sparse_header = FALSE</code> to specify that we
actually want to include the “summerschool” as a header.</p></li>
</ul>
</div>
<div id="section-variable-names-in-tables" class="section level3">
<h3>4.3 Variable names in tables</h3>
<p>So far we’ve used variable names as labels in our table. In contrast
to Stata, R allows for labels with white space, and we could therefore
rename the variables to give nicer looking names in our table. However,
we can also just assign a “label” when creating the table as shown
below:</p>
<pre class="r"><code># load modelsummary
library(&quot;modelsummary&quot;)
# create a summary stat table

datasummary((`Female`=female)+
            (`Parental schooling (years)`=parental_schooling)+
            (`Parental income (log)`=parental_lincome)+
            (`Received reminder letter`=letter)+
            (`Test Score`=test_score)~
            (`Attended summer school`=Factor(summerschool))*
              (Mean+SD),
            sparse_header = FALSE,
            data=filter(analysisdata,year==2))</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
0
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
1
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Female
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
0.50
</td>
<td style="text-align:right;">
0.53
</td>
<td style="text-align:right;">
0.50
</td>
</tr>
<tr>
<td style="text-align:left;">
Parental schooling (years)
</td>
<td style="text-align:right;">
11.03
</td>
<td style="text-align:right;">
0.74
</td>
<td style="text-align:right;">
11.67
</td>
<td style="text-align:right;">
1.33
</td>
</tr>
<tr>
<td style="text-align:left;">
Parental income (log)
</td>
<td style="text-align:right;">
14.35
</td>
<td style="text-align:right;">
0.52
</td>
<td style="text-align:right;">
14.81
</td>
<td style="text-align:right;">
0.79
</td>
</tr>
<tr>
<td style="text-align:left;">
Received reminder letter
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.29
</td>
<td style="text-align:right;">
0.43
</td>
<td style="text-align:right;">
0.49
</td>
</tr>
<tr>
<td style="text-align:left;">
Test Score
</td>
<td style="text-align:right;">
−0.29
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
0.34
</td>
<td style="text-align:right;">
1.05
</td>
</tr>
</tbody>
</table>
</div>
<div id="section-exporting-our-table-to-microsoft-word"
class="section level3">
<h3>4.4 Exporting our table to Microsoft Word</h3>
<p>To save our <code>datasummary()</code> table to Microsoft Word or
Latex, we use the same expression as with
<code>datasummary_skim()</code>, as illustrated below:</p>
<pre class="r"><code># load modelsummary
library(&quot;modelsummary&quot;)
# create a summary stat table
datasummary((`Female`=female)+
            (`Parental schooling (years)`=parental_schooling)+
            (`Parental income (log)`=parental_lincome)+
            (`Received reminder letter`=letter)+
            (`Test Score`=test_score)~
            (Mean+SD+P25+P50+P75),
            sparse_header = FALSE,
            data=filter(analysisdata,year==2),
            output = &#39;tab_descriptive_statistics.docx&#39;)</code></pre>
</div>
</div>
<div id="section-descriptive-charts" class="section level2">
<h2>5 Descriptive charts</h2>
<p>The <em>ggplot</em> world is covered in detail in <a
href="https://hhsievertsen.shinyapps.io/r_introduction_UoB_2/">R
introduction</a>, but let us briefly cover a few charts here as well.
You will also see more charts in later chapters.</p>
<div id="section-a-scatter-plot" class="section level3">
<h3>5.1 A scatter plot</h3>
<p>Our first chart is a scatter plot. We are interested in whether test
score and parental income are correlated. We therefore create a scatter
plot of test scores in year 5 against parental income. We add a fitted
line as well.</p>
<p>In the following example we</p>
<ol style="list-style-type: decimal">
<li>Initiate a <code>ggplot()</code> object using the
<em>analysisdata</em> filtered to only include year 5.</li>
<li>Specify that <em>parental_lincome</em> should be used on the x-axis
and <em>test_score</em> on the y-axis in <code>aes()</code> inside
<code>ggplot()</code>.</li>
<li>Use <code>geom_smooth()</code> to include a fitted line.</li>
<li>Use <code>geom_point()</code> to add the scatters.</li>
</ol>
<p>This chart does not look very good. You can use the tools from the <a
href="https://hhsievertsen.shinyapps.io/r_introduction_UoB_2/">R
introduction</a> to polish it (or you can use the hints to get some
suggestions).</p>
<div class="tutorial-exercise" data-label="merge4" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># load ggplot2
library(&quot;ggplot2&quot;)
# create a scatter plot with a fitted line
ggplot(analysisdata%&gt;%filter(year==5),  
       aes(x=parental_lincome,y=test_score))+
       geom_smooth() +
       geom_point()</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge4-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Make the line green by setting the color to the html colour code &quot;#145c21&quot;

# load ggplot2
library(&quot;ggplot2&quot;)
# create a scatter plot with a fitted line
ggplot(analysisdata%&gt;%filter(year==5),  
       aes(x=parental_lincome,y=test_score))+
       geom_smooth(color=&quot;#145c21&quot;) +
       geom_point()</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="merge4-hint-2"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Make the scatters green, partly transparent (with alpha=), and change the size of them.

# load ggplot2
library(&quot;ggplot2&quot;)
# create a scatter plot with a fitted line
ggplot(analysisdata%&gt;%filter(year==5),  
       aes(x=parental_lincome,y=test_score))+
       geom_smooth(color=&quot;#145c21&quot;) +
       geom_point(alpha=0.1,size=0.85,color=&quot;#63a668&quot;)</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="merge4-hint-3"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Change the colour of the background and the grid lines

# load ggplot2
library(&quot;ggplot2&quot;)
# create a scatter plot with a fitted line
ggplot(analysisdata%&gt;%filter(year==5),  
       aes(x=parental_lincome,y=test_score))+
       geom_smooth(color=&quot;#145c21&quot;) +
       geom_point(alpha=0.1,size=0.85,color=&quot;#63a668&quot;)+
  theme(panel.background = element_rect(fill=&quot;#ededed&quot;,color=&quot;#ededed&quot;),
             plot.background = element_rect(fill=&quot;#ededed&quot;,color=&quot;#ededed&quot;),
             panel.grid.major = element_line(colour=&quot;#a3a3a3&quot;,size=0.1))</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="merge4-hint-4"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Change the axes titles and add an overall title

# load ggplot2
library(&quot;ggplot2&quot;)
# create a scatter plot with a fitted line
ggplot(analysisdata%&gt;%filter(year==5),  
       aes(x=parental_lincome,y=test_score))+
       geom_smooth(color=&quot;#145c21&quot;) +
       geom_point(alpha=0.1,size=0.85,color=&quot;#63a668&quot;)+
       theme(panel.background = element_rect(fill=&quot;#ededed&quot;,color=&quot;#ededed&quot;),
             plot.background = element_rect(fill=&quot;#ededed&quot;,color=&quot;#ededed&quot;),
             panel.grid.major = element_line(colour=&quot;#a3a3a3&quot;,size=0.1))+
  labs(x=&quot;Log(Parental Income)&quot;,y=&quot;Test Score (Mean=0,SD=1)&quot;, title=&quot;Test scores &amp; Parental income&quot;)</code></pre>
</div>
</div>
<div id="section-bar-chart-and-boxplot" class="section level3">
<h3>5.2 Bar chart and boxplot</h3>
<p>Okay, we observe that test score is correlated with parental income.
That is not surprising. Now let’s also create charts to assesses whether
summer school attendance is correlated with individual characteristics.
We first create a scatter plot of parental schooling and test scores in
year 5 (before the summer school). This is just like above, but with
schooling instead of income. Secondly, we create a bar chart showing
average test score in year 5 (before the summer school) by summer school
attendance. Thirdly, we create box plots of parental income by summer
school attendance. There are a few additional tricks in the following
code:</p>
<ul>
<li>We first create the basic <code>ggplot()</code> object where we load
the data and specify the theme. This object is called
<em>rawchart</em></li>
<li>We then create 3 charts based on <em>rawchart</em>. Each chart is
saved under a name.</li>
<li>We use <code>geom_bar()</code> to create a bar chart. We set
<code>stat="summary",fun="mean"</code> to tell R to create a bar chart
showing the mean of <em>test_score</em>.</li>
<li>We use <code>labs()</code> to specify the axes titles.</li>
<li>We use <code>geom_boxplot()</code> to create a box plot.</li>
<li>We use the patchwork package to combine several charts in one
chart.</li>
<li>Use <code>ggsave()</code> to save the chart to a <em>png</em>
file.</li>
</ul>
<pre class="r"><code># Load patchwork 
library(&quot;patchwork&quot;)
# Create raw chart element
rawchart&lt;-ggplot(analysisdata%&gt;%filter(year==4),x=as.factor(fill))+
          theme_classic()
# Create bar chart of pre summer school test score and summer school 
p1&lt;-rawchart+
       geom_smooth(aes(x=parental_schooling,y=test_score)) +
       geom_point(aes(x=parental_schooling,y=test_score),alpha=0.1)+
       labs(x=&quot;Parental schooling&quot;, y=&quot;Test Score Year 5&quot;)
# Create bar chart of pre summer school test score and summer school 
p2&lt;-rawchart+
       geom_bar(aes(x=as.factor(summerschool),y=test_score),
                    stat=&quot;summary&quot;,fun=&quot;mean&quot;)+
       labs(y=&quot;Test Score Year 5&quot;, x=&quot;Attended Summer School&quot;)
# Create bar chart of parental schooling and summer school attendance
p3&lt;-rawchart+
              geom_boxplot(aes(x=as.factor(summerschool),y=parental_lincome))+
       labs(y=&quot;Parental Income (log)&quot;, x=&quot;Attended Summer School&quot;)
# Combine charts
p1/(p2+p3)
# Export chart
ggsave(&quot;fig1.png&quot;)</code></pre>
<p><img src="applied_econ_with_R_Dynamic_files/figure-html/ch5-3-1.png" width="600" style="display: block; margin: auto;" /></p>
<p>The three charts above show us that test scores are correlated with
parental background (the scatter plot), that those who attended the
summer school had better test scores before the summer school, and that
parental account is correlated with summer school attendance (the box
plot). In short:</p>
<div class="figure" style="text-align: center">
<img src="images/selectionbias.png" alt=" " width="40%" />
<p class="caption">
</p>
</div>
</div>
<div id="section-histogram-density-charts" class="section level3">
<h3>5.3 Histogram &amp; density charts</h3>
<p>Let’s compare the test score distribution in year 6 (after the summer
school) for those who attended the summer school with those who did not.
We create a histogram and add a line showing the estimated density
distributions. In the hints we also change the colour scheme, the legend
labels, the legend position, and do a few minor tweaks.</p>
<div class="tutorial-exercise" data-label="merge5" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># create a histogram and density chart
ggplot(filter(analysisdata,year==6),
       aes(x=test_score,fill=as.factor(summerschool)))+
       geom_histogram(aes(y=..density..),bins = 50,alpha=0.5,
                       position=&quot;identity&quot;,color=&quot;white&quot;)+
       geom_density()</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge5-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># create a histogram and density chart
ggplot(filter(analysisdata,year==6),
       aes(x=test_score,fill=as.factor(summerschool)))+
       geom_histogram(aes(y=..density..),bins = 50,alpha=0.5,
                       position=&quot;identity&quot;,color=&quot;white&quot;)+
       geom_density(alpha=0.0,size=1,show.legend= FALSE)+
       theme_minimal()+
       labs(y=&quot;Density&quot;,x=&quot;Test score&quot;,fill=&quot; &quot;)+
       scale_fill_brewer(palette=&quot;Set2&quot;,labels=c(&quot;No summer school&quot;,&quot;Summer school&quot;))+
       theme(legend.position=&quot;top&quot;)</code></pre>
</div>
</div>
<div id="section-the-joy-division-album-cover-chart"
class="section level3">
<h3>5.4 The Joy Division Album Cover chart</h3>
<div class="figure" style="text-align: center">
<img src="images/joydivision.png" alt=" " width="40%" />
<p class="caption">
</p>
</div>
<p>The next chart is inspired by a Joy Division album cover unknown
pleasures (read more <a
href="https://blogs.scientificamerican.com/sa-visual/pop-culture-pulsar-origin-story-of-joy-division-s-unknown-pleasures-album-cover-video/">here</a>).
We use <code>geom_density_ridges()</code> from the <em>ggridges</em>
package.</p>
<p>Our goal is to compare the test score distribution for those who
received the summer school reminder letter with those who did not. We
are already making a step into the next chapter and assessing at the
Randomized Control Trial in two dimensions. First, the test score
comparisons before year 6 are informative about whether the
randomization worked. Secondly, the test score comparisons from year 6
and later are informative about the reduced form effect.</p>
<pre class="r"><code># Load ggridges
library(&quot;ggridges&quot;)

# create a ggridges  chart
ggplot(analysisdata,aes(y=as.factor(year),x=test_score,fill=as.factor(letter) ))+
        geom_density_ridges(  alpha = .7, scale=1.5,color = &quot;white&quot;, from = -2.5, to = 2.5)+
        theme_minimal()+
        theme_ridges(grid = FALSE)+
  scale_y_discrete(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
        scale_fill_brewer(palette=&quot;Set1&quot;,labels=c(&quot;No letter&quot;,&quot;Letter&quot;))+
        labs(x=&quot;Test Score&quot;,y=&quot;Year&quot;,fill=&quot; &quot;,
            title=&quot;Test score distribution by reminder letter status  &amp; year&quot;)+
        theme(legend.position=&quot;top&quot;,aspect.ratio=4/3,plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="applied_econ_with_R_Dynamic_files/figure-html/ch5-5-1.png" width="750" style="display: block; margin: auto;" /></p>
<p>The chart above tells a convincing story. In the first five years the
distribution of test scores is essentially identical across those who
received and those who did not receive a reminder letter. That indicates
that the randomisation worked as intended. After year 5 the test score
distribution of those who received a reminder letter shifted to the
right compared to those who did not receive a letter suggesting a
reduced form effect of the letter on our outcome. Let’s analyse that in
the next sections.</p>
</div>
</div>
<div id="section-balancing-tables" class="section level2">
<h2>6 Balancing tables</h2>
<p>The last chart suggested that the letter that was randomly sent to
some families to remind them about the summer school worked. The test
score distribution of the children that received the letter shifted to
the right. Importantly, the charts also suggested that there was no
difference prior to the summer school. Let us now test that
formally.</p>
<div id="section-pairwise-t-test" class="section level3">
<h3>6.1 Pairwise t-test</h3>
<p>We can conduct a t-test in R using <code>t.test()</code>.
Specifically, we specify the formula
<code>test_score~summerschool</code> to test whether the mean
<em>test_score</em> is significantly different across the two groups
specified by <em>summerschool</em>. Let’s do that for year 5 data:</p>
<div class="tutorial-exercise" data-label="merge6" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Filter year 5
df&lt;-analysisdata%&gt;%filter(year==5)
# Conduct a t test
t.test(test_score~summerschool,data=df)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<p>Note that <code>df&lt;-analysisdata%&gt;%filter(year==5)</code> might
look a bit unfamiliar to you. It simply a different way of writing
<code>df&lt;-filter(analysisdata,year==5)</code>. But what is the right
interpretation of the test result?</p>
<p><div class="panel-heading tutorial-quiz-title">Quiz</div></p>
<div class="panel panel-default">
<div data-label="quiz2-1" class="tutorial-question panel-body">
<div id="quiz2-1-answer_container" class="shiny-html-output"></div>
<div id="quiz2-1-message_container" class="shiny-html-output"></div>
<div id="quiz2-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<p>One feature of R that I really appreciate (especially compared to
Stata) is that I can skip steps and directly insert functions within
other functions. For example if I know that I am not going to use the
selected dataset again, we don’t need to create it first. We can simply
specify the selection criteria in the data argument of
<code>t.test()</code> as shown by the hints to the code block above,
where we use year 4 instead of year 5.</p>
</div>
<div id="section-a-publication-ready-table-of-mean-comparisons"
class="section level3">
<h3>6.2 A publication ready table of mean comparisons</h3>
<p>If we want to create a nice looking balancing table and insert it in
Word, we can use <code>datasummary_balance()</code> from the
<em>modelsummary</em> package. We load the <em>estimatr</em> package
because it enables <code>datasummary_balance()</code> to calculate and
include the pairwise t-tests directly into the table</p>
<pre class="r"><code># Load libraries
library(modelsummary)
library(estimatr)
# Filter and modify data
testdata&lt;-filter(analysisdata,year==5)
testdata&lt;-ungroup(testdata)
testdata&lt;-mutate(testdata,Treated=ifelse(letter==1,&quot;Letter&quot;,&quot;No Letter&quot;))
testdata&lt;-select(testdata,female,parental_schooling,parental_lincome,test_score,Treated)
testdata&lt;-rename(testdata,`Female`=female,
          `Parental schooling (years)`=parental_schooling,
          `Parental income (log)`=parental_lincome,
          `Test Score`=test_score)
     
# Table with balancing test
datasummary_balance(~Treated,
                    data = testdata,
                    title = &quot;Balance of pre-treatment variables&quot;,
                    notes = &quot;Notes: This is a brilliant table!&quot;,
                    fmt= &#39;%.5f&#39;,
                    dinm_statistic = &quot;p.value&quot;)</code></pre>
<table style="NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;" class="table">
<caption>
Balance of pre-treatment variables
</caption>
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Letter (N=861)
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
No Letter (N=2619)
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2">
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Std. Dev.
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Std. Dev.
</th>
<th style="text-align:right;">
Diff. in Means
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Female
</td>
<td style="text-align:right;">
0.52033
</td>
<td style="text-align:right;">
0.49988
</td>
<td style="text-align:right;">
0.51355
</td>
<td style="text-align:right;">
0.49991
</td>
<td style="text-align:right;">
-0.00677
</td>
<td style="text-align:right;">
0.73032
</td>
</tr>
<tr>
<td style="text-align:left;">
Parental schooling (years)
</td>
<td style="text-align:right;">
11.31359
</td>
<td style="text-align:right;">
0.97129
</td>
<td style="text-align:right;">
11.32952
</td>
<td style="text-align:right;">
1.14573
</td>
<td style="text-align:right;">
0.01593
</td>
<td style="text-align:right;">
0.69028
</td>
</tr>
<tr>
<td style="text-align:left;">
Parental income (log)
</td>
<td style="text-align:right;">
14.56467
</td>
<td style="text-align:right;">
0.66201
</td>
<td style="text-align:right;">
14.56289
</td>
<td style="text-align:right;">
0.70338
</td>
<td style="text-align:right;">
-0.00178
</td>
<td style="text-align:right;">
0.94629
</td>
</tr>
<tr>
<td style="text-align:left;">
Test Score
</td>
<td style="text-align:right;">
-0.01950
</td>
<td style="text-align:right;">
0.99990
</td>
<td style="text-align:right;">
0.00641
</td>
<td style="text-align:right;">
1.00014
</td>
<td style="text-align:right;">
0.02591
</td>
<td style="text-align:right;">
0.50968
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; " colspan="100%">
<sup></sup> Notes: This is a brilliant table!
</td>
</tr>
</tfoot>
</table>
<p>This looks nice!The table suggests that all variables are well
balanced across treated (receiving a letter) and untreated.</p>
<p>As before, we can simply add the option
<code>output=tab_balancing.docx</code> if we want to export the table to
Microsoft Word.</p>
</div>
</div>
<div id="section-ordinary-least-squares" class="section level2">
<h2>7 Ordinary Least Squares</h2>
<p>Our goal is now to estimate the following reduced form relationship
between test score in year 6 and an indicator for receiving a reminder
letter using Ordinary Least Squares (OLS)</p>
<p><span
class="math inline">\(testscore_i=\beta_0+\beta_1Letter_i+u_i\)</span>.</p>
<div id="section-ols-estimation-with-with-lm" class="section level3">
<h3>7.1 OLS estimation with with <code>lm()</code></h3>
<p>We can run OLS with <code>lm()</code> (linear models). We first enter
a formula of the form:</p>
<ul>
<li><code>y~x1+x2+...</code></li>
</ul>
<p>followed by the</p>
<ul>
<li><code>data=...</code> command.</li>
</ul>
<p>Below is an example based on a univariate regression between
testscore and the indicator for receiving the letter. Try to change the
code to also include parental_lincome in the regression (see hints).</p>
<div class="tutorial-exercise" data-label="merge7" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Our first ordinary least squares regression
lm(test_score~letter,data=filter(analysisdata,year==6))</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge7-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># ... now also with parental_lincome
lm(test_score~letter+parental_lincome,data=filter(analysisdata,year==6))</code></pre>
</div>
<p>The output from <code>lm()</code> is a bit disappointing. But fear
not. We can use the universal <code>summary()</code> function to get a
bit more information out of <code>lm()</code>:</p>
<div class="tutorial-exercise" data-label="merge8" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Summary of ordinary least squares regression
summary(lm(test_score~letter,data=filter(analysisdata,year==6)))</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge8-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># ... now also with parental lincome
summary(lm(test_score~letter+parental_lincome,data=filter(analysisdata,year==6)))</code></pre>
</div>
<p>A nice feature of R is that we can assign basically everything to a
name and then use it later. In the code block below we first run a
regression and store it under the name <em>model1</em>. We then later
call these regression results back when using the <code>summary()</code>
command (see hints!). In the following example we include a few
covariates in the regression:</p>
<div class="tutorial-exercise" data-label="merge9" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code>#  Ordinary Least Squares regression
model1&lt;-lm(test_score~parental_schooling+parental_lincome+letter+female,data=filter(analysisdata,year==6))</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge9-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code>#  Ordinary Least Squares regression
model1&lt;-lm(test_score~parental_schooling+parental_lincome+letter+female,data=filter(analysisdata,year==6))
# Summary of model1
summary(model1)</code></pre>
</div>
</div>
<div id="section-ols-with-the-feols-function" class="section level3">
<h3>7.2 OLS with the feols() function</h3>
<p>I am a big fan of running regressions with <strong>reghdfe</strong>
if in Stata. Luckily R has something quite similar. That is
<code>feols()</code> from the <em>fixest</em> package. This function
expects a formula of the form:</p>
<ul>
<li><code>y~x1+x2+..|fixed effects|IV specification,cluster=..</code></li>
</ul>
<p>In the following example we run a linear regression without fixed
effects, but standard errors clustered on the school level.</p>
<pre class="r"><code># Load packages
library(fixest)
# Select data
regdata&lt;-filter(analysisdata,year==6)
# Regression
m1&lt;-feols(test_score~letter+parental_lincome+female+parental_schooling, cluster=&quot;school_id&quot;,data=regdata)
# Summary of regression
summary(m1)</code></pre>
<pre><code>## OLS estimation, Dep. Var.: test_score
## Observations: 3,481 
## Standard-errors: Clustered (school_id) 
##                      Estimate Std. Error    t value   Pr(&gt;|t|)    
## (Intercept)        -14.559587   0.334389 -43.540865  &lt; 2.2e-16 ***
## letter               0.205574   0.027142   7.574038 2.3813e-08 ***
## parental_lincome     1.018485   0.035655  28.565105  &lt; 2.2e-16 ***
## female              -0.014251   0.020766  -0.686275 4.9799e-01    
## parental_schooling  -0.027892   0.022328  -1.249180 2.2159e-01    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## RMSE: 0.725574   Adj. R2: 0.472785</code></pre>
<div class="tutorial-exercise-support" data-label="regdata"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Select data
regdata&lt;-filter(analysisdata,year==6)</code></pre>
</div>
<p>Brilliant. Let’s now try to output such regressions to a nice looking
table. We use the <code>modelsummary()</code> function from
<em>modelsummary</em> for that. In the following example we</p>
<ol style="list-style-type: decimal">
<li><p>Run two regressions and store them as <em>models</em> in a list.
The first regression is above, in the second regression we add fixed
effects for year and school.</p></li>
<li><p>Use <code>modelsummary()</code> to output the results of the
regression results stored in <em>models</em>.</p></li>
<li><p>Specify that <code>modelsummary()</code> excludes the coefficient
on the intercept.</p></li>
<li><p>Specify that parentheses should include standard errors with
<code>statistic='std.error'</code>.</p></li>
<li><p>Specify the formatting of the numbers with
<code>fmt=..</code>.</p></li>
</ol>
<div class="tutorial-exercise" data-label="merge10" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Load  modelsummary
library(modelsummary)

# Regressions
models&lt;-list(
  m1&lt;-feols(test_score~letter+parental_lincome+female+parental_schooling, cluster=&quot;school_id&quot;,data=regdata),
  m2&lt;-feols(test_score~letter+parental_lincome+female+parental_schooling|school_id+year, cluster=&quot;school_id&quot;,data=regdata)
  )
# Generate table
modelsummary(models, stars = TRUE,statistic = &#39;std.error&#39;,
             fmt= &#39;%.4f&#39;,
              coef_omit= &#39;(Intercept)&#39;)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.setup":"regdata","exercise.checker":"NULL"}</script>
</div>
<p>Just like in earlier examples, we can output our table to Microsoft
Word or Latex with <code>output=..</code>. The results show that those
received a letter have a 0.2SD higher test score in year 6. There are
many other settings that we can specify to polish our table. But let us
move on.</p>
</div>
</div>
<div id="section-logit-probit" class="section level2">
<h2>8 Logit &amp; probit</h2>
<p>Okay, from section 6 we conclude that the randomization worked and
that receiving the letter is as good as random. From section 7 we know
that those that received a letter have a 0.2SD higher test score in year
6. But that is the intend to treat effect. Let us now scale that by the
first stage effect. We are interested in the link between receiving a
letter and attending the summer school:</p>
<p><span class="math display">\[summerschool_i=g(letter_i)\]</span></p>
<div id="section-estimating-the-lpm-with-ols" class="section level3">
<h3>8.1 Estimating the LPM with OLS</h3>
<p>Let us first consider the linear probability model and estimate</p>
<p><span
class="math display">\[summerschool_i=\beta1+\beta_2letter_i+\gamma&#39;X_i+u_i\]</span></p>
<p>We already know how to do that. We can use <code>lm()</code> or
<code>felm()</code>, but let us use this as a change to add a row with
the mean of the dependent variable. We do that by calculating the
statistics we want to add and add them to the table with
<code>add_rows=...</code> as shown below.</p>
<div class="tutorial-exercise" data-label="ch8-1" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Estimate LPM (the first stage)
models&lt;-list(
  m1&lt;-feols(summerschool ~letter, cluster=&quot;school_id&quot;,data=regdata),
  m2&lt;-feols(summerschool ~letter+parental_schooling+parental_lincome+female| school_id+year,cluster=&quot;school_id&quot;,data=regdata)
  )
# Store the mean of dependent variable in a data frame
added_stats&lt;-tibble(&quot;Mean of Dep. &quot;,m1=mean(regdata$summerschool),m2=mean(regdata$summerschool))
# Generate table
modelsummary(models, stars = TRUE,statistic = &#39;std.error&#39;,  
             fmt= &#39;%.4f&#39;,add_rows = added_stats,
              coef_omit= &#39;(Intercept)&#39;)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.setup":"regdata","exercise.checker":"NULL"}</script>
</div>
<p>So receiving the letter increases the likelihood of attending the
summer school by 44% which is a about a 100% increase compared to the
mean of 0.46.</p>
</div>
<div id="section-logit-probit-1" class="section level3">
<h3>8.2 Logit &amp; Probit</h3>
<p>We might not be happy with the linear probability model and decide to
go for a logit or probit instead. Let’s have a look at that. We can use
<code>glm()</code> to estimate logit and probit models. We specify the
link function as an option as shown below for probit.</p>
<div class="tutorial-exercise" data-label="merge11" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code>#  Estimate a binary outcomes model using a probit
probit_results &lt;- glm(summerschool ~letter, data = regdata, family = binomial(link=&quot;probit&quot;))
# Print the results
summary(probit_results)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.setup":"regdata","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge11-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># ... now a the logit: we simply change the link to &quot;logit&quot;

##  Estimate a binary outcomes model using a logit
logit_results &lt;- glm(summerschool ~letter+parental_lincome+female+parental_schooling, data = regdata, family = binomial(link=&quot;logit&quot;))
# Print the results
summary(logit_results)</code></pre>
</div>
<p>Try to change the code above to get the logit estimates (see hints!).
Let’s compute the average marginal effects.</p>
</div>
<div id="section-marginal-effects" class="section level3">
<h3>8.3 Marginal effects</h3>
<p>We can use <code>margins()</code> to obtain average marginal effects.
We simply use the <code>margins()</code> function on the objects storing
or probit and logit estimates. We can also include these directly in a
nice looking table.</p>
<pre class="r"><code># Load margins package
library(&quot;margins&quot;)
# Select data
regdata&lt;-filter(analysisdata,year==6)
##  Estimate a binary outcomes model using a logit and probit
logit_results &lt;- glm(summerschool ~letter+parental_lincome+female+parental_schooling, data = regdata, family = binomial(link=&quot;logit&quot;))
probit_results &lt;- glm(summerschool ~letter+parental_lincome+female+parental_schooling, data = regdata, family = binomial(link=&quot;probit&quot;))
# Estimate linear probability model
lpm&lt;-feols(summerschool ~letter+parental_schooling+parental_lincome+female, cluster=&quot;school_id&quot;,data=regdata)
#  Compute marginal effects
mfx_logit&lt;- margins(logit_results)
mfx_probit&lt;- margins(probit_results)
# Include in table
modelsummary(list(&quot;LPM&quot;=lpm,&quot;Logit&quot;=mfx_logit,&quot;Probit&quot;=mfx_probit))</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
LPM
</th>
<th style="text-align:center;">
Logit
</th>
<th style="text-align:center;">
Probit
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:center;">
−2.783
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.237)
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
letter
</td>
<td style="text-align:center;">
0.443
</td>
<td style="text-align:center;">
0.409
</td>
<td style="text-align:center;">
0.414
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.014)
</td>
<td style="text-align:center;">
(0.013)
</td>
<td style="text-align:center;">
(0.014)
</td>
</tr>
<tr>
<td style="text-align:left;">
parental_schooling
</td>
<td style="text-align:center;">
0.036
</td>
<td style="text-align:center;">
0.047
</td>
<td style="text-align:center;">
0.049
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.012)
</td>
<td style="text-align:center;">
(0.012)
</td>
<td style="text-align:center;">
(0.012)
</td>
</tr>
<tr>
<td style="text-align:left;">
parental_lincome
</td>
<td style="text-align:center;">
0.187
</td>
<td style="text-align:center;">
0.183
</td>
<td style="text-align:center;">
0.178
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.023)
</td>
<td style="text-align:center;">
(0.017)
</td>
<td style="text-align:center;">
(0.017)
</td>
</tr>
<tr>
<td style="text-align:left;">
female
</td>
<td style="text-align:center;">
0.010
</td>
<td style="text-align:center;">
0.010
</td>
<td style="text-align:center;">
0.010
</td>
</tr>
<tr>
<td style="text-align:left;box-shadow: 0px 1px">
</td>
<td style="text-align:center;box-shadow: 0px 1px">
(0.011)
</td>
<td style="text-align:center;box-shadow: 0px 1px">
(0.015)
</td>
<td style="text-align:center;box-shadow: 0px 1px">
(0.015)
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Obs.
</td>
<td style="text-align:center;">
3481
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
R2
</td>
<td style="text-align:center;">
0.255
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
R2 Adj.
</td>
<td style="text-align:center;">
0.254
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
RMSE
</td>
<td style="text-align:center;">
0.43
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Std.Errors
</td>
<td style="text-align:center;">
by: school_id
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
</td>
</tr>
</tbody>
</table>
<p>The results are very similar across the columns, and we will proceed
with the LPM in a two stage least squares approach to estimate the
IV.</p>
</div>
</div>
<div id="section-instrumental-variables" class="section level2">
<h2>9 Instrumental Variables</h2>
<p>We estimated the reduced form relationship between receiving a
reminder letter and test scores to be 0.2SD. We have also estimated the
first stage to be around 0.4. What does this mean for the IV estimator
(hint: use the Wald Estimator)?</p>
<p><div class="panel-heading tutorial-quiz-title">Quiz</div></p>
<div class="panel panel-default">
<div data-label="quiz3-1" class="tutorial-question panel-body">
<div id="quiz3-1-answer_container" class="shiny-html-output"></div>
<div id="quiz3-1-message_container" class="shiny-html-output"></div>
<div id="quiz3-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div>
<p>Let us estimate the instrumental variable specification explicitly to
see whether it maps with our answer above. I will show you two
methods.</p>
<div id="section-iv-using-the-ivreg-function." class="section level3">
<h3>9.1 IV using the ivreg() function.</h3>
<p>We first use the <code>ivreg()</code> function from the <em>AER</em>
package. AER does not refer to the American Economic Review, but to
Applied Economics with R. The syntax is as follows</p>
<ul>
<li><code>ivreg(outcome equation| exogenous variables, data)</code></li>
</ul>
<pre class="r"><code># Load the AER package
library(AER)
# Select data
regdata&lt;-filter(analysisdata,year==6)
# Estimate IV specification with
summary(ivreg(test_score~summerschool+female+parental_lincome+parental_schooling|
                         female+parental_lincome+parental_schooling+letter,data=regdata))</code></pre>
<pre><code>## 
## Call:
## ivreg(formula = test_score ~ summerschool + female + parental_lincome + 
##     parental_schooling | female + parental_lincome + parental_schooling + 
##     letter, data = regdata)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -2.339871 -0.442354  0.008259  0.436036  2.565493 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        -13.26937    0.30480 -43.535  &lt; 2e-16 ***
## summerschool         0.46360    0.05761   8.047 1.15e-15 ***
## female              -0.01872    0.02207  -0.848  0.39627    
## parental_lincome     0.93185    0.02892  32.217  &lt; 2e-16 ***
## parental_schooling  -0.04473    0.01690  -2.647  0.00817 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.65 on 3476 degrees of freedom
## Multiple R-Squared: 0.578,   Adjusted R-squared: 0.5775 
## Wald test: 974.7 on 4 and 3476 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The estimate is very close to the 0.5 we obtained above at
0.46SD.</p>
</div>
<div id="section-iv-using-the-feols-function." class="section level3">
<h3>9.2 IV using the feols() function.</h3>
<p>Let us now reuse the <code>feols()</code> function. Just like we can
use <em>reghdfe</em> in Stata for IV, <code>felm()</code> also allows us
to estimate IV specifications. We don’t include fixed effect, so we
simply set this part to 0. We then add a new part with the first
stag</p>
<pre class="r"><code># Estimate IV specification with felm 
m1&lt;-feols(test_score~parental_lincome+female+parental_schooling| # Outcome eq.
           0|                                                    # Fixed effects
           summerschool~letter                                   # First stage
           ,cluster=&quot;school_id&quot;                                  # Cluster var
            ,data=regdata)
# Summary of results
summary(m1)</code></pre>
<pre><code>## TSLS estimation, Dep. Var.: test_score, Endo.: summerschool, Instr.: letter
## Second stage: Dep. Var.: test_score
## Observations: 3,481 
## Standard-errors: Clustered (school_id) 
##                      Estimate Std. Error    t value   Pr(&gt;|t|)    
## (Intercept)        -13.269370   0.325477 -40.768964  &lt; 2.2e-16 ***
## fit_summerschool     0.463600   0.058812   7.882797 1.0788e-08 ***
## parental_lincome     0.931852   0.030669  30.383780  &lt; 2.2e-16 ***
## female              -0.018723   0.018995  -0.985649 3.3246e-01    
## parental_schooling  -0.044732   0.019098  -2.342270 2.6241e-02 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## RMSE: 0.649555   Adj. R2: 0.577472
## F-test (1st stage), summerschool: stat = 685.7, p &lt; 2.2e-16  , on 1 and 3,476 DoF.
##                       Wu-Hausman: stat =  38.0, p = 7.859e-10, on 1 and 3,475 DoF.</code></pre>
<p>The coefficients are as above, but note that the standard errors are
slightly different now, as we cluster them on the school level. Note
also that <code>feols()</code> tells us that the F-stat on the excluded
instrument is 686.</p>
</div>
<div id="section-a-complete-iv-table" class="section level3">
<h3>9.3 A complete IV table</h3>
<p>Let us finish the IV section by creating a complete IV table showing
the raw correlation between test score and summer school attendance, the
reduced form, the first stage, and the IV estimate.</p>
<p>Note that in the example below we use <code>coef_map=</code> to
rename coefficients, specify the coefficients to include, and to let two
coefficients with different names appear in the same row
(<em>summerschool</em> and <em>fit_summerschool</em> ).</p>
<p>Note that in the code block below I included a few “REPLACEME”. The
code will not work unless you change them to the right code.</p>
<div class="tutorial-exercise" data-label="merge12" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Estimate OLS
OLS&lt;-feols(test_score~summerschool+parental_lincome+female+parental_schooling,cluster=&quot;school_id&quot;,data=regdata)
# Estimate reduced form 
RF&lt;-feols(REPLACEME~letter+parental_lincome+female+parental_schooling,cluster=&quot;school_id&quot;,data=regdata)
# Estimate first stage 
FS&lt;-feols(REPLACEME~letter+parental_lincome+female+parental_schooling,cluster=&quot;school_id&quot;,data=regdata)
# Estimate IV specification 
IV&lt;-feols(test_score~parental_lincome+female+parental_schooling| # Outcome eq.
           0|                                                    # Fixed effects
           REPLACEME~letter                                   # First stage
           ,cluster=&quot;school_id&quot;                                  # Cluster var
            ,data=regdata)
# Combine results
IVresults&lt;-list(&quot;OLS&quot;=OLS,&quot;RF&quot;=RF,&quot;FS&quot;=FS,&quot;IV&quot;=IV)
# Coefficients
cm &lt;- c(&#39;fit_summerschool&#39; = &#39;Summer School&#39;,
        &#39;summerschool&#39; = &#39;Summer School&#39;,&#39;parental_lincome&#39; = &#39;Parental Income&#39;, 
        &#39;letter&#39; = &#39;Reminder letter&#39;, &quot;female&quot;=&quot;Female&quot;,&quot;parental_schooling&quot;=&quot;Parental Schooling&quot;)
# Output Table
modelsummary(IVresults, stars = TRUE,statistic = &#39;std.error&#39;,  
             fmt= &#39;%.4f&#39;,coef_map=cm)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.setup":"regdata","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge12-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Estimate OLS
OLS&lt;-feols(test_score~summerschool+parental_lincome+female+parental_schooling,cluster=&quot;school_id&quot;,data=regdata)
# Estimate reduced form 
RF&lt;-feols(test_score~letter+parental_lincome+female+parental_schooling,cluster=&quot;school_id&quot;,data=regdata)
# Estimate first stage 
FS&lt;-feols(summerschool~letter+parental_lincome+female+parental_schooling,cluster=&quot;school_id&quot;,data=regdata)
# Estimate IV specification 
IV&lt;-feols(test_score~parental_lincome+female+parental_schooling| # Outcome eq.
           0|                                                    # Fixed effects
           summerschool~letter                                   # First stage
           ,cluster=&quot;school_id&quot;                                  # Cluster var
            ,data=regdata)
# Combine results
IVresults&lt;-list(&quot;OLS&quot;=OLS,&quot;RF&quot;=RF,&quot;FS&quot;=FS,&quot;IV&quot;=IV)
# Coefficients
cm &lt;- c(&#39;fit_summerschool&#39; = &#39;Summer School&#39;,
        &#39;summerschool&#39; = &#39;Summer School&#39;,&#39;parental_lincome&#39; = &#39;Parental Income&#39;, 
        &#39;letter&#39; = &#39;Reminder letter&#39;, &quot;female&quot;=&quot;Female&quot;,&quot;parental_schooling&quot;=&quot;Parental Schooling&quot;)
# Output Table
modelsummary(IVresults, stars = TRUE,statistic = &#39;std.error&#39;,  
             fmt= &#39;%.4f&#39;,coef_map=cm)</code></pre>
</div>
<p>The first column shows that ignoring the selection problem and
estimating the relationship between test score and summer school
conditional controls, leads to a coefficient of 0.78SD. As expected this
coefficient is larger than the IV estimate of 0.47SD shown in the fourth
column of the table. The descriptive charts in chapter 5 suggested that
the children who attended the summer school already had better test
scores before the summer school and that their parents have higher
incomes and completed more years of education. The coefficient in the
first column above is therefore likely capturing not only the causal
effect of the summer school but also other unobserved characteristics
that are positively linked to test scores and summer school
attendance.</p>
</div>
</div>
<div id="section-difference-in-differences" class="section level2">
<h2>10 Difference-in-Differences</h2>
<p>Our IV story analysis was quite convincing. It is based on an RCT and
the coefficient was smaller than the “naive OLS” as we expected. But let
us not stop there. Let us also exploit that we have test scores of the
children both before and after the summer school. We can therefore
estimate a difference-in-differences specification:</p>
<p><span
class="math display">\[test_score=\beta1+\beta_2summerschool_i+\beta_3after_i+\beta_4after_i\times
summerschool+\gamma&#39;X_i+u_i\]</span></p>
<p>Where after refers to test scores after attending the summer
school.</p>
<div id="section-inspecting-the-common-trends" class="section level3">
<h3>10.1 Inspecting the common trends</h3>
<p>A crucial assumption behind the difference-in-differences approach is
that the treated and control groups would have similar developments over
time in the absence of treatment. We therefore want to create line
charts of test scores over year to see whether the trends are similar in
years without treatment.</p>
<p>We use this as a change to first collapse the data on the year times
summerschool level using <code>group_by()</code> and
<code>summarise()</code>. There are a few “REPLACEME”s that you need to
replace in order to make the code run. Hint: check the hints if you are
stuck!</p>
<div class="tutorial-exercise" data-label="merge14" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Collapse data on the year X summer school level
df&lt;-XYZ1(analysisdata,year,summerschool)
# Calculate the mean test score by year
df&lt;-XYZ2(df,test_score=mean(test_score))
# Create a chart
ggplot(df,XYZ3(x=year,y=test_score,color=as.factor(summerschool)))+
  geom_line(size=1)+
  theme_classic()+
  theme(legend.position = &quot;top&quot;)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.setup":"regdata","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge14-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Collapse data on the year X summer school level
df&lt;-group_by(analysisdata,year,summerschool)
# Calculate the mean test score by year
df&lt;-summarise(df,test_score=mean(test_score))
# Create a chart
ggplot(df,aes(x=year,y=test_score,color=as.factor(summerschool)))+
  geom_line(size=1)+
  theme_classic()+
  theme(legend.position = &quot;top&quot;)</code></pre>
</div>
<p>We observe a small drop in the treatment group just before the summer
school and a small increase in the control group. That looks a bit
worrying, but otherwise the trends are very similar.</p>
</div>
<div id="section-estimating-the-difference-in-differences-model"
class="section level3">
<h3>10.2 Estimating the Difference-in-Differences model</h3>
<p>Let’s estimate the simple difference-in-differences model using only
data on year 5 and year 6 with the <code>lm()</code> function. We first
modify the data to create an after indicator, using
<code>mutate()</code> and <code>ifelse()</code>.</p>
<pre class="r"><code># Select  year 5 and year 6 observations
df&lt;-analysisdata%&gt;%filter(year%in%c(5,6))
# Generate an after indicator and the interaction between after and summer school
df&lt;-mutate(df,after=ifelse(year==6,1,0),afterXsumerschool=after*summerschool)
# Estimate the DiD regression and save the results in an element called m1
m&lt;-lm(test_score~summerschool+after+afterXsumerschool,data=df)
# Print the results
summary(m)</code></pre>
<pre><code>## 
## Call:
## lm(formula = test_score ~ summerschool + after + afterXsumerschool, 
##     data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.5110 -0.5365  0.0618  0.6110  3.3407 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -0.18058    0.02098  -8.606   &lt;2e-16 ***
## summerschool       0.38887    0.03079  12.629   &lt;2e-16 ***
## after             -0.34717    0.02967 -11.701   &lt;2e-16 ***
## afterXsumerschool  0.74794    0.04354  17.177   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9059 on 6957 degrees of freedom
## Multiple R-squared:  0.1796, Adjusted R-squared:  0.1792 
## F-statistic: 507.6 on 3 and 6957 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Very good. We observe that the difference-in-differences coefficient
is 0.75. Suggesting that attending the summer school increases the test
scores by 0.75SD. That is larger than the estimate we got above with the
IV approach. Maybe it is because we only use year 5 and 6 and we saw
this odd trend going from year 5 to year 6. Let’s therefore try to add
all years.</p>
<p>We will use the <code>feols()</code> function to estimate the the
difference-in-differences specification on all years (we could also use
<code>lm()</code>). The first approach is the traditional approach with
after, after X treated, and treated indicators. In the second approach
we include year fixed effects instead of the after dummy. In the third
approach we add controls.</p>
<p>Note that I again added a few “REPLACEME” that you need to change
before the code will run. Don’t worry, you can always check the
hints.</p>
<div class="tutorial-exercise" data-label="merge13" data-caption="Code"
data-completion="1" data-diagnostics="1" data-startover="1"
data-lines="0">
<pre class="text"><code># Modify data
df&lt;-mutate(analysisdata,after=ifelse(year&gt;5,1,0),afterXsummerschool=after*summerschool)
df&lt;-rename(df,school=summerschool)
# Estimate DiD without controls and fixed effects
m1&lt;-feols(test_score~school+REPLACEME+after,cluster=&quot;school_id&quot;,data=df)
# Estimate DiD without controls
m2&lt;-feols(test_score~school+afterXsummerschool|school_id+year,cluster=&quot;school_id&quot;,data=df)
# Estimate DiD  with controls
m3&lt;-feols(test_score~afterXsummerschool+school+parental_lincome+female+parental_schooling
         |school_id+year,cluster=&quot;school_id&quot;,data=df)
# Leave year 5 out to avoid dip
m4&lt;-feols(test_score~afterXsummerschool+school+parental_lincome+REPLACEME+parental_schooling
         |school_id+year,cluster=&quot;school_id&quot;,data=filter(df,year!=5))

# Coefficients
cm &lt;- c(&#39;afterXsummerschool&#39;  = &#39;Summer School X After&#39;,
        &#39;school&#39;        = &#39;Summer School&#39;,
        &#39;after&#39;=&#39;After&#39;)
# Output Table
modelsummary(list(m1,m2,m3,m4), stars = TRUE,statistic = &#39;std.error&#39;,  
             statistic_override = vcov,
             fmt= &#39;%.4f&#39;,coef_map=cm)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":false,"error":false,"message":false,"exercise.df_print":"paged","exercise.setup":"regdata","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="merge13-hint-1"
data-caption="Code" data-completion="1" data-diagnostics="1"
data-startover="1" data-lines="0">
<pre class="text"><code># Modify data
df&lt;-mutate(analysisdata,after=ifelse(year&gt;5,1,0),afterXsummerschool=after*summerschool)
df&lt;-rename(df,school=summerschool)
# Estimate DiD without controls and fixed effects
m1&lt;-feols(test_score~school+afterXsummerschool+after,cluster=&quot;school_id&quot;,data=df)
# Estimate DiD without controls
m2&lt;-feols(test_score~school+afterXsummerschool|school_id+year,cluster=&quot;school_id&quot;,data=df)
# Estimate DiD  with controls
m3&lt;-feols(test_score~afterXsummerschool+school+parental_lincome+female+parental_schooling
         |school_id+year,cluster=&quot;school_id&quot;,data=df)
# Leave year 5 out to avoid dip
m4&lt;-feols(test_score~afterXsummerschool+school+parental_lincome+female+parental_schooling
         |school_id+year,cluster=&quot;school_id&quot;,data=filter(df,year!=5))

# Coefficients
cm &lt;- c(&#39;afterXsummerschool&#39;  = &#39;Summer School X After&#39;,
        &#39;school&#39;        = &#39;Summer School&#39;,
        &#39;after&#39;=&#39;After&#39;)
# Output Table
modelsummary(list(m1,m2,m3,m4), stars = TRUE,statistic = &#39;std.error&#39;,  
             statistic_override = vcov,
             fmt= &#39;%.4f&#39;,coef_map=cm )</code></pre>
</div>
<p>The treatment effects estimate are all around 0.6SD, which is
slightly larger than the IV estimate, but smaller than the “naive OLS.
The last column above shows the DiD estimate excluding year 5 where we
observe the worrying deviations from the trend. As expected, this
specification gives a slightly smaller coefficient of 0.54SD, it is
however, still slightly larger than our IV estimate.</p>
<p><br><br> <strong>That is it!</strong> You made it to the end of my
tutorial. Well done! <br> 
<script type="application/shiny-prerendered" data-context="server-start">

library("aewr")
library("tidyverse")
library("skimr")
library("readstata13")
library("fixest")
library("sjPlot")
library("psych")
library(learnr)
library("openxlsx")
knitr::opts_chunk$set(echo = FALSE)
</script>


<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ch2-9b-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ch2-9b-code-editor`)), session)
output$`tutorial-exercise-ch2-9b-output` <- renderUI({
  `tutorial-exercise-ch2-9b-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ch2-10-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ch2-10-code-editor`)), session)
output$`tutorial-exercise-ch2-10-output` <- renderUI({
  `tutorial-exercise-ch2-10-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-1", question = structure("How many variables does the merged dataset contain", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_9d91e73",     option = "7", value = "7", label = structure("7", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_e368116",     option = "10", value = "10", label = structure("10", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_a8ffdc",     option = "15", value = "15", label = structure("15", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_5ee628f",     option = "17", value = "17", label = structure("17", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz-1-answer", question = "quiz-1"), loading = structure("<strong>Loading:<\u002fstrong> \nHow many variables does the merged dataset contain\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = FALSE,     seed = 640015459.20197, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ch3-1e-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ch3-1e-code-editor`)), session)
output$`tutorial-exercise-ch3-1e-output` <- renderUI({
  `tutorial-exercise-ch3-1e-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ch3-3-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ch3-3-code-editor`)), session)
output$`tutorial-exercise-ch3-3-output` <- renderUI({
  `tutorial-exercise-ch3-3-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ch3-4-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ch3-4-code-editor`)), session)
output$`tutorial-exercise-ch3-4-output` <- renderUI({
  `tutorial-exercise-ch3-4-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ch3-5-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ch3-5-code-editor`)), session)
output$`tutorial-exercise-ch3-5-output` <- renderUI({
  `tutorial-exercise-ch3-5-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ch3-6-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ch3-6-code-editor`)), session)
output$`tutorial-exercise-ch3-6-output` <- renderUI({
  `tutorial-exercise-ch3-6-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ch4-1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ch4-1-code-editor`)), session)
output$`tutorial-exercise-ch4-1-output` <- renderUI({
  `tutorial-exercise-ch4-1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge3-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge3-code-editor`)), session)
output$`tutorial-exercise-merge3-output` <- renderUI({
  `tutorial-exercise-merge3-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge4-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge4-code-editor`)), session)
output$`tutorial-exercise-merge4-output` <- renderUI({
  `tutorial-exercise-merge4-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge5-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge5-code-editor`)), session)
output$`tutorial-exercise-merge5-output` <- renderUI({
  `tutorial-exercise-merge5-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge6-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge6-code-editor`)), session)
output$`tutorial-exercise-merge6-output` <- renderUI({
  `tutorial-exercise-merge6-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz2-1", question = structure("What is the correct interpretation of the test?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_f9488e0",     option = "The p-value is < 2.2e-16, and using a 5% significance level we therefore  reject the null hypothesis that the difference in means between those who attended and those who did not attend is zero. In other words, the test score before was significantly different across those who attended and those who did not attend.",     value = "The p-value is < 2.2e-16, and using a 5% significance level we therefore  reject the null hypothesis that the difference in means between those who attended and those who did not attend is zero. In other words, the test score before was significantly different across those who attended and those who did not attend.",     label = structure("The p-value is &lt; 2.2e-16, and using a 5% significance level we therefore  reject the null hypothesis that the difference in means between those who attended and those who did not attend is zero. In other words, the test score before was significantly different across those who attended and those who did not attend.", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_ce439fc",     option = "The p-value is < 2.2e-16, and using a 5% (or even higher) significance level we therefore cannot reject the null hypothesis that the difference in means between those who attended and those who did not attend is zero. In other words, the test score before was not significantly different across those who attended and those who did not attend.",     value = "The p-value is < 2.2e-16, and using a 5% (or even higher) significance level we therefore cannot reject the null hypothesis that the difference in means between those who attended and those who did not attend is zero. In other words, the test score before was not significantly different across those who attended and those who did not attend.",     label = structure("The p-value is &lt; 2.2e-16, and using a 5% (or even higher) significance level we therefore cannot reject the null hypothesis that the difference in means between those who attended and those who did not attend is zero. In other words, the test score before was not significantly different across those who attended and those who did not attend.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_e7f6ed1",     option = "The p-value is 0.2082893 , and using a 5% (or even higher) significance level we therefore  reject the null hypothesis that the difference in means between those who attended and those who did not attend is zero. In other words, the test score before was significantly different across those who attended and those who did not attend.",     value = "The p-value is 0.2082893 , and using a 5% (or even higher) significance level we therefore  reject the null hypothesis that the difference in means between those who attended and those who did not attend is zero. In other words, the test score before was significantly different across those who attended and those who did not attend.",     label = structure("The p-value is 0.2082893 , and using a 5% (or even higher) significance level we therefore  reject the null hypothesis that the difference in means between those who attended and those who did not attend is zero. In other words, the test score before was significantly different across those who attended and those who did not attend.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz2-1-answer", question = "quiz2-1"), loading = structure("<strong>Loading:<\u002fstrong> \nWhat is the correct interpretation of the test?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = FALSE,     seed = 940357996.562112, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge7-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge7-code-editor`)), session)
output$`tutorial-exercise-merge7-output` <- renderUI({
  `tutorial-exercise-merge7-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge8-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge8-code-editor`)), session)
output$`tutorial-exercise-merge8-output` <- renderUI({
  `tutorial-exercise-merge8-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge9-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge9-code-editor`)), session)
output$`tutorial-exercise-merge9-output` <- renderUI({
  `tutorial-exercise-merge9-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge10-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge10-code-editor`)), session)
output$`tutorial-exercise-merge10-output` <- renderUI({
  `tutorial-exercise-merge10-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-ch8-1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-ch8-1-code-editor`)), session)
output$`tutorial-exercise-ch8-1-output` <- renderUI({
  `tutorial-exercise-ch8-1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge11-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge11-code-editor`)), session)
output$`tutorial-exercise-merge11-output` <- renderUI({
  `tutorial-exercise-merge11-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz3-1", question = structure("Given the reduced form estimate of 0.2SD and a first stage coefficient of 0.4, the IV estimate is expected to be", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_3dcece9",     option = "About 0.5  based on dividing the reduced form estimate of 0.2 by the first stage of 0.4.",     value = "About 0.5  based on dividing the reduced form estimate of 0.2 by the first stage of 0.4.",     label = structure("About 0.5  based on dividing the reduced form estimate of 0.2 by the first stage of 0.4.", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_3d16f75",     option = "About 0.08  based on multiplying the reduced form estimate of 0.2 by the first stage of 0.4.",     value = "About 0.08  based on multiplying the reduced form estimate of 0.2 by the first stage of 0.4.",     label = structure("About 0.08  based on multiplying the reduced form estimate of 0.2 by the first stage of 0.4.", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_bdc3bdb",     option = "About 0.2, because it is always the same as the reduced form",     value = "About 0.2, because it is always the same as the reduced form",     label = structure("About 0.2, because it is always the same as the reduced form", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz3-1-answer", question = "quiz3-1"), loading = structure("<strong>Loading:<\u002fstrong> \nGiven the reduced form estimate of 0.2SD and a first stage coefficient of 0.4, the IV estimate is expected to be\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = FALSE,     seed = 1448654909.82542, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge12-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge12-code-editor`)), session)
output$`tutorial-exercise-merge12-output` <- renderUI({
  `tutorial-exercise-merge12-result`()
})
</script>


<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge14-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge14-code-editor`)), session)
output$`tutorial-exercise-merge14-output` <- renderUI({
  `tutorial-exercise-merge14-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-merge13-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-merge13-code-editor`)), session)
output$`tutorial-exercise-merge13-output` <- renderUI({
  `tutorial-exercise-merge13-result`()
})
</script>
</p>
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["header-attrs"]},{"type":"character","attributes":{},"value":["2.14"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pandoc"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["header-attrs.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.14"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/united.min.css"]},{"type":"character","attributes":{},"value":["<style>h1 {font-size: 34px;}\n       h1.title {font-size: 38px;}\n       h2 {font-size: 30px;}\n       h3 {font-size: 24px;}\n       h4 {font-size: 18px;}\n       h5 {font-size: 16px;}\n       h6 {font-size: 12px;}\n       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}\n       pre:not([class]) { background-color: white }<\/style>"]},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.14"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.14"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.14"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.14"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.14"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["3.6.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/3.6.0"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery-3.6.0.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquerylib"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.1.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.14"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["kePrint"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["kePrint-0.0.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["kePrint.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["lightable"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lightable-0.0.1"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["lightable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["kePrint"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["kePrint-0.0.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["kePrint.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["lightable"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lightable-0.0.1"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["lightable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["kePrint"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["kePrint-0.0.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["kePrint.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["lightable"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lightable-0.0.1"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["lightable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["kePrint"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["kePrint-0.0.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["kePrint.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["lightable"]},{"type":"character","attributes":{},"value":["0.0.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lightable-0.0.1"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["lightable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["kableExtra"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["1.3.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152]}},"value":[{"type":"character","attributes":{},"value":["abind","AER","aewr","assertthat","backports","base","base64enc","bayestestR","boot","broom","bslib","car","carData","cellranger","checkmate","cli","codetools","colorspace","compiler","crayon","data.table","datasets","datawizard","DBI","dbplyr","digest","dplyr","dreamerr","effectsize","ellipsis","emmeans","estimability","estimatr","evaluate","fansi","farver","fastmap","fixest","forcats","Formula","fs","gargle","generics","ggeffects","ggplot2","ggridges","glue","googledrive","googlesheets4","graphics","grDevices","grid","gtable","haven","highr","hms","htmltools","htmlwidgets","httpuv","httr","insight","jquerylib","jsonlite","kableExtra","knitr","labeling","later","lattice","learnr","lifecycle","lme4","lmtest","lubridate","magrittr","margins","markdown","MASS","Matrix","methods","mgcv","mime","minqa","mnormt","modelr","modelsummary","multcomp","munsell","mvtnorm","nlme","nloptr","numDeriv","openxlsx","parallel","parameters","patchwork","performance","pillar","pkgconfig","plyr","prediction","promises","psych","purrr","R6","RColorBrewer","Rcpp","readr","readstata13","readxl","repr","reprex","rlang","rmarkdown","rprojroot","rstudioapi","rvest","sandwich","sass","scales","shiny","sjlabelled","sjmisc","sjPlot","sjstats","skimr","splines","stats","stringi","stringr","survival","svglite","systemfonts","tables","TH.data","tibble","tidyr","tidyselect","tidyverse","tools","tzdb","utf8","utils","vctrs","viridisLite","webshot","withr","xfun","xml2","xtable","yaml","zip","zoo"]},{"type":"character","attributes":{},"value":["1.4-5","1.2-10","0.5.0","0.2.1","1.4.1","4.2.1","0.1-3","0.13.0","1.3-28","1.0.0","0.3.1","3.1-0","3.0-5","1.1.0","2.1.0","3.3.0","0.2-18","2.0-3","4.2.1","1.5.1","1.14.2","4.2.1","0.6.3","1.1.3","2.2.1","0.6.29","1.0.9","1.2.3","0.8.2","0.3.2","1.8.2","1.4.1","1.0.0","0.15","1.0.3","2.1.1","1.1.0","0.10.4","0.5.1","1.2-4","1.5.2","1.2.0","0.1.3","1.1.4","3.3.6","0.5.3","1.6.2","2.0.0","1.0.0","4.2.1","4.2.1","4.2.1","0.3.0","2.5.0","0.9","1.1.1","0.5.2","1.5.4","1.6.5","1.4.3","0.18.6","0.1.4","1.8.0","1.3.4","1.39","0.4.2","1.3.0","0.20-45","0.10.1","1.0.1","1.1-30","0.9-40","1.8.0","2.0.3","0.3.26","1.1","7.3-57","1.4-1","4.2.1","1.8-40","0.12","1.2.4","2.1.1","0.1.8","1.0.2","1.4-19","0.5.0","1.1-3","3.1-157","2.0.3","2016.8-1.1","4.2.5","4.2.1","0.19.0","1.1.2","0.10.0","1.7.0","2.0.3","1.8.7","0.3.14","1.2.0.1","2.2.9","0.3.4","2.5.1","1.1-3","1.0.9","2.1.2","0.10.0","1.4.0","1.1.4","2.0.1","1.0.4","2.14","2.0.3","0.13","1.0.2","3.0-2","0.4.1","1.2.0","1.7.2","1.2.0","2.8.9","2.8.11","0.18.1","2.1.4","4.2.1","4.2.1","1.7.6","1.4.0","3.3-1","2.1.0","1.0.4","0.9.6","1.1-1","3.1.7","1.2.0","1.1.2","1.3.2","4.2.1","0.3.0","1.2.2","4.2.1","0.4.1","0.4.0","0.5.3","2.5.0","0.31","1.3.3","1.8-4","2.3.5","2.2.0","1.8-10"]}]}]}
</script>
<!--/html_preserve-->
</div>
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Applied Economics
with R for UoB students</h2>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
